

function classColors()
{
    var out = [

        {className: 'PC.CA1.1', taxonomy: 'PC CA1', color: '#FFCCCC', subcolor: '#FFCCCC'},
        {className: 'PC.CA1.2', taxonomy: 'PC CA1', color: '#FFCCCC', subcolor: '#ffd8d8'},
        {className: 'PC.CA1.3', taxonomy: 'PC CA1', color: '#FFCCCC', subcolor: '#ffe8e8'},
        {className: 'PC.CA2', taxonomy: 'PC subtypes', color: '#CCFFCC', subcolor: '#CCFFCC'},
        {className: 'PC.CA3', taxonomy: 'PC subtypes', color: '#CCFFCC', subcolor: '#ddffdd'},
        {className: 'Eryth.1', taxonomy: 'NonNeuron', color: '#7F7F7F', subcolor: '#CCCCCC'},
        {className: 'Eryth.2', taxonomy: 'NonNeuron', color: '#7F7F7F', subcolor: '#C7C7C7'},
        {className: 'Oligo.1', taxonomy: 'NonNeuron', color: '#7F7F7F', subcolor: '#C2C2C2'},
        {className: 'Oligo.2', taxonomy: 'NonNeuron', color: '#7F7F7F', subcolor: '#BEBEBE'},
        {className: 'Oligo.3', taxonomy: 'NonNeuron', color: '#7F7F7F', subcolor: '#BDBDBD'},
        {className: 'Oligo.4', taxonomy: 'NonNeuron', color: '#7F7F7F', subcolor: '#B8B8B8'},
        {className: 'Oligo.5', taxonomy: 'NonNeuron', color: '#7F7F7F', subcolor: '#7F7F7F'},
        {className: 'Vsmc', taxonomy: 'NonNeuron', color: '#7F7F7F', subcolor: '#B3B3B3'},
        {className: 'Endo', taxonomy: 'NonNeuron', color: '#7F7F7F', subcolor: '#ADADAD'},
        {className: 'Astro.1', taxonomy: 'NonNeuron', color: '#7F7F7F', subcolor: '#ABABAB'},
        {className: 'Astro.2', taxonomy: 'NonNeuron', color: '#7F7F7F', subcolor: '#A8A8A8'},
        {className: 'Astro.3', taxonomy: 'NonNeuron', color: '#7F7F7F', subcolor: '#A6A6A6'},
        {className: 'Astro.4', taxonomy: 'NonNeuron', color: '#7F7F7F', subcolor: '#A1A1A1'},
        {className: 'Astro.5', taxonomy: 'NonNeuron', color: '#7F7F7F', subcolor: '#9C9C9C'},
        {className: 'Zero', taxonomy: 'Zero', color: '#000000', subcolor: '#000000'},
        {className: 'Cacna2d1.Lhx6.Reln', taxonomy: 'null', color: '#b3de69', subcolor: '#60861D'},
        {className: 'Cacna2d1.Lhx6.Vwa5a', taxonomy: 'null', color: '#b3de69', subcolor: '#77A725'},
        {className: 'Cacna2d1.Ndnf.Cxcl14', taxonomy: 'null', color: '#b3de69', subcolor: '#b3de69'},
        {className: 'Cacna2d1.Ndnf.Npy', taxonomy: 'null', color: '#b3de69', subcolor: '#8FC92C'},
        {className: 'Cacna2d1.Ndnf.Rgs10', taxonomy: 'null', color: '#b3de69', subcolor: '#A2D747'},
        {className: 'Calb2.Cntnap5a.Igfbp6', taxonomy: 'null', color: '#ffff00', subcolor: '#ffff00'},
        {className: 'Calb2.Cntnap5a.Rspo3', taxonomy: 'null', color: '#ffff00', subcolor: '#ffff83'},
        {className: 'Calb2.Cntnap5a.Vip', taxonomy: 'null', color: '#ffff00', subcolor: '#ffff5d'},
        {className: 'Calb2.Cryab', taxonomy: 'null', color: '#ffff00', subcolor: '#ffffdb'},
        {className: 'Calb2.Vip.Gpd1', taxonomy: 'null', color: '#ffff00', subcolor: '#ffffcb'},
        {className: 'Calb2.Vip.Igfbp4', taxonomy: 'null', color: '#ffff00', subcolor: '#ffffb7'},
        {className: 'Calb2.Vip.Nos1', taxonomy: 'null', color: '#ffff00', subcolor: '#ffffa0'},
        {className: 'Cck.Calca', taxonomy: 'null', color: '#fb8072', subcolor: '#ffddd2'},
        {className: 'Cck.Cxcl14.Calb1.Igfbp5', taxonomy: 'null', color: '#fb8072', subcolor: '#ff8261'},
        {className: 'Cck.Cxcl14.Calb1.Kctd12', taxonomy: 'null', color: '#fb8072', subcolor: '#ff5734'},
        {className: 'Cck.Cxcl14.Calb1.Tac2', taxonomy: 'null', color: '#fb8072', subcolor: '#fe3e1e'},
        {className: 'Cck.Cxcl14.Calb1.Tnfaip8l3', taxonomy: 'null', color: '#fb8072', subcolor: '#ff9677'},
        {className: 'Cck.Cxcl14.Slc17a8', taxonomy: 'null', color: '#fb8072', subcolor: '#ff6e4a'},
        {className: 'Cck.Cxcl14.Vip', taxonomy: 'null', color: '#fb8072', subcolor: '#f91800'},
        {className: 'Cck.Lmo1.Npy', taxonomy: 'null', color: '#fb8072', subcolor: '#ffe7e0'},
        {className: 'Cck.Lmo1.Vip.Crh', taxonomy: 'null', color: '#fb8072', subcolor: '#ffc6b3'},
        {className: 'Cck.Lmo1.Vip.Fam19a2', taxonomy: 'null', color: '#fb8072', subcolor: '#ffd2c4'},
        {className: 'Cck.Lmo1.Vip.Tac2', taxonomy: 'null', color: '#fb8072', subcolor: '#ffb7a0'},
        {className: 'Cck.Lypd1', taxonomy: 'null', color: '#fb8072', subcolor: '#ffa78c'},
        {className: 'Cck.Sema5a', taxonomy: 'null', color: '#fb8072', subcolor: '#fdf0ec'},
        {className: 'Choroid', taxonomy: 'null', color: '#e6e6fa', subcolor: '#e6e6fa'},
        {className: 'Microglia.1', taxonomy: 'null', color: '#8dd3c7', subcolor: '#8dd3c7'},
        {className: 'Microglia.2', taxonomy: 'null', color: '#8dd3c7', subcolor: '#cfece6'},
        {className: 'Ntng1.Chrm2', taxonomy: 'null', color: '#80b1d3', subcolor: '#80b1d3'},
        {className: 'Ntng1.Rgs10', taxonomy: 'null', color: '#80b1d3', subcolor: '#5e9ad2'},
        {className: 'Ntng1.Synpr', taxonomy: 'null', color: '#80b1d3', subcolor: '#2883d1'},
        {className: 'Pvalb.C1ql1.Cpne5', taxonomy: 'null', color: '#e5c494', subcolor: '#DFB77C'},
        {className: 'Pvalb.C1ql1.Npy', taxonomy: 'null', color: '#e5c494', subcolor: '#e5c494'},
        {className: 'Pvalb.C1ql1.Pvalb', taxonomy: 'null', color: '#e5c494', subcolor: '#D7A55B'},
        {className: 'Pvalb.Tac1.Akr1c18', taxonomy: 'null', color: '#e5c494', subcolor: '#CF943A'},
        {className: 'Pvalb.Tac1.Nr4a2', taxonomy: 'null', color: '#e5c494', subcolor: '#73501C'},
        {className: 'Pvalb.Tac1.Sst', taxonomy: 'null', color: '#e5c494', subcolor: '#946724'},
        {className: 'Pvalb.Tac1.Syt2', taxonomy: 'null', color: '#e5c494', subcolor: '#B57E2C'},
        {className: 'Sst.Cryab', taxonomy: 'null', color: '#fdb462', subcolor: '#FDC686'},
        {className: 'Sst.Erbb4.Crh', taxonomy: 'null', color: '#fdb462', subcolor: '#FDBC72'},
        {className: 'Sst.Erbb4.Rgs10', taxonomy: 'null', color: '#fdb462', subcolor: '#FDB462'},
        {className: 'Sst.Erbb4.Th', taxonomy: 'null', color: '#fdb462', subcolor: '#FDC686'},
        {className: 'Sst.Nos1', taxonomy: 'null', color: '#fdb462', subcolor: '#B56203'},
        {className: 'Sst.Npy.Cort', taxonomy: 'null', color: '#fdb462', subcolor: '#C96D03'},
        {className: 'Sst.Npy.Mgat4c', taxonomy: 'null', color: '#fdb462', subcolor: '#FB8D0E'},
        {className: 'Sst.Npy.Serpine2', taxonomy: 'null', color: '#fdb462', subcolor: '#F18204'},
        {className: 'Sst.Npy.Zbtb20', taxonomy: 'null', color: '#fdb462', subcolor: '#DD7703'},
        {className: 'Sst.Pnoc.Calb1.Igfbp5', taxonomy: 'null', color: '#fdb462', subcolor: '#FC9622'},
        {className: 'Sst.Pnoc.Calb1.Pvalb', taxonomy: 'null', color: '#fdb462', subcolor: '#FCA036'},
        {className: 'Sst.Pnoc.Pvalb', taxonomy: 'null', color: '#fdb462', subcolor: '#FCA94A'},
        {className: 'Vip.Crh.C1ql1', taxonomy: 'null', color: '#bebada', subcolor: '#bebada'},
        {className: 'Vip.Crh.Pcp4', taxonomy: 'null', color: '#bebada', subcolor: '#a895db'},
        {className: 'Other', taxonomy: 'null', color: '#e5c494', subcolor: '#e5c494'},



    ];

    return out
}