

function classColorsCodes()
{
    var out = [

        {className: 'Astro.1', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Astro.2', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Astro.3', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Astro.4', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Astro.5', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Cacna2d1.Lhx6.Reln', NickName: 'MGE NGF', colorGroup: 'ngf', color: '#FF00E6'},
        {className: 'Cacna2d1.Lhx6.Vwa5a', NickName: 'Ivy', colorGroup: 'ngf', color: '#FF00E6'},
        {className: 'Cacna2d1.Ndnf.Cxcl14', NickName: 'CGE NGF', colorGroup: 'ngf', color: '#FF00E6'},
        {className: 'Cacna2d1.Ndnf.Npy', NickName: 'CGE NGF', colorGroup: 'ngf', color: '#FF00E6'},
        {className: 'Cacna2d1.Ndnf.Rgs10', NickName: 'CGE NGF', colorGroup: 'ngf', color: '#FF00E6'},
        {className: 'Calb2.Cntnap5a.Igfbp6', NickName: 'IS1', colorGroup: 'vip', color: '#FFE600'},
        {className: 'Calb2.Cntnap5a.Rspo3', NickName: 'IS1', colorGroup: 'vip', color: '#FFE600'},
        {className: 'Calb2.Cntnap5a.Vip', NickName: 'IS1', colorGroup: 'vip', color: '#FFE600'},
        {className: 'Calb2.Cryab', NickName: 'IS1', colorGroup: 'vip', color: '#FFE600'},
        {className: 'Calb2.Vip.Gpd1', NickName: 'IS3', colorGroup: 'vip', color: '#FFE600'},
        {className: 'Calb2.Vip.Igfbp4', NickName: 'IS3', colorGroup: 'vip', color: '#FFE600'},
        {className: 'Calb2.Vip.Nos1', NickName: 'IS3', colorGroup: 'vip', color: '#FFE600'},
        {className: 'Cck.Calca', NickName: 'Cck', colorGroup: 'cnr1', color: '#FF0000'},
        {className: 'Cck.Cxcl14.Calb1.Igfbp5', NickName: 'Cck Cxcl14', colorGroup: 'cnr1', color: '#FF0000'},
        {className: 'Cck.Cxcl14.Calb1.Kctd12', NickName: 'Cck Cxcl14', colorGroup: 'cnr1', color: '#FF0000'},
        {className: 'Cck.Cxcl14.Calb1.Tac2', NickName: 'Cck Cxcl14', colorGroup: 'cnr1', color: '#FF0000'},
        {className: 'Cck.Cxcl14.Calb1.Tnfaip8l3', NickName: 'Cck Cxcl14', colorGroup: 'cnr1', color: '#FF0000'},
        {className: 'Cck.Cxcl14.Slc17a8', NickName: 'Cck Cxcl14 Slc17a8', colorGroup: 'cnr1', color: '#FF0000'},
        {className: 'Cck.Cxcl14.Vip', NickName: 'Cck Cxcl14 Vip', colorGroup: 'cnr1', color: '#FF0000'},
        {className: 'Cck.Lmo1.Npy', NickName: 'Cck Vip', colorGroup: 'cnr1', color: '#FF0000'},
        {className: 'Cck.Lmo1.Vip.Crh', NickName: 'Cck Vip', colorGroup: 'cnr1', color: '#FF0000'},
        {className: 'Cck.Lmo1.Vip.Fam19a2', NickName: 'Cck Vip', colorGroup: 'cnr1', color: '#FF0000'},
        {className: 'Cck.Lmo1.Vip.Tac2', NickName: 'Cck Vip', colorGroup: 'cnr1', color: '#FF0000'},
        {className: 'Cck.Lypd1', NickName: 'Cck', colorGroup: 'cnr1', color: '#FF0000'},
        {className: 'Cck.Sema5a', NickName: 'Cck', colorGroup: 'cnr1', color: '#FF0000'},
        {className: 'Choroid', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Endo', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Eryth.1', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Eryth.2', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Microglia.1', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Microglia.2', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Ntng1.Chrm2', NickName: 'Trilaminar', colorGroup: 'proj', color: '#FF8000'},
        {className: 'Ntng1.Rgs10', NickName: 'Rad retrohip', colorGroup: 'proj', color: '#FF8000'},
        {className: 'Ntng1.Synpr', NickName: 'Proj', colorGroup: 'proj', color: '#FF8000'},
        {className: 'Oligo.1', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Oligo.2', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Oligo.3', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Oligo.4', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Oligo.5', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'PC.CA1.1', NickName: 'PC', colorGroup: 'pc', color: '#00FF00'},
        {className: 'PC.CA1.2', NickName: 'PC', colorGroup: 'pc', color: '#00FF00'},
        {className: 'PC.CA1.3', NickName: 'PC', colorGroup: 'pc', color: '#00FF00'},
        {className: 'PC.CA2', NickName: 'PC CA2', colorGroup: 'pc2', color: '#73E500'},
        {className: 'PC.CA3', NickName: 'PC CA3', colorGroup: 'pc2', color: '#73E500'},
        {className: 'Pvalb.C1ql1.Cpne5', NickName: 'AAC', colorGroup: 'pvalb', color: '#5C33FF'},
        {className: 'Pvalb.C1ql1.Npy', NickName: 'AAC', colorGroup: 'pvalb', color: '#5C33FF'},
        {className: 'Pvalb.C1ql1.Pvalb', NickName: 'AAC', colorGroup: 'pvalb', color: '#5C33FF'},
        {className: 'Pvalb.Tac1.Akr1c18', NickName: 'Bistrat', colorGroup: 'pvalb', color: '#5C33FF'},
        {className: 'Pvalb.Tac1.Nr4a2', NickName: 'Basket', colorGroup: 'pvalb', color: '#5C33FF'},
        {className: 'Pvalb.Tac1.Sst', NickName: 'Bistrat', colorGroup: 'pvalb', color: '#5C33FF'},
        {className: 'Pvalb.Tac1.Syt2', NickName: 'Basket', colorGroup: 'pvalb', color: '#5C33FF'},
        {className: 'Sst.Cryab', NickName: 'Sst', colorGroup: 'sst', color: '#00B2FF'},
        {className: 'Sst.Erbb4.Crh', NickName: 'O-Bi', colorGroup: 'sst', color: '#00B2FF'},
        {className: 'Sst.Erbb4.Rgs10', NickName: 'O-Bi', colorGroup: 'sst', color: '#00B2FF'},
        {className: 'Sst.Erbb4.Th', NickName: 'O-Bi', colorGroup: 'sst', color: '#00B2FF'},
        {className: 'Sst.Nos1', NickName: 'Nos1', colorGroup: 'sst', color: '#00B2FF'},
        {className: 'Sst.Npy.Cort', NickName: 'HSept', colorGroup: 'sst', color: '#00B2FF'},
        {className: 'Sst.Npy.Mgat4c', NickName: 'HSept', colorGroup: 'sst', color: '#00B2FF'},
        {className: 'Sst.Npy.Serpine2', NickName: 'HSept', colorGroup: 'sst', color: '#00B2FF'},
        {className: 'Sst.Npy.Zbtb20', NickName: 'HSept', colorGroup: 'sst', color: '#00B2FF'},
        {className: 'Sst.Pnoc.Calb1.Igfbp5', NickName: 'OLM', colorGroup: 'sst', color: '#00B2FF'},
        {className: 'Sst.Pnoc.Calb1.Pvalb', NickName: 'OLM', colorGroup: 'sst', color: '#00B2FF'},
        {className: 'Sst.Pnoc.Pvalb', NickName: 'OLM', colorGroup: 'sst', color: '#00B2FF'},
        {className: 'Vip.Crh.C1ql1', NickName: 'IS2', colorGroup: 'vip', color: '#FFE600'},
        {className: 'Vip.Crh.Pcp4', NickName: 'CckCxcl14Vip', colorGroup: 'vip', color: '#FFE600'},
        {className: 'Vsmc', NickName: 'Non Neuron', colorGroup: 'non_neuron', color: '#FFFFFF'},
        {className: 'Zero', NickName: 'Zero', colorGroup: 'Zero', color: '#000000'},

        // I added this
        {className: 'Other', NickName: 'Other', colorGroup: 'Other', color: '#C0C0C0'},


    ];

    return out
}